/*
 * Copyright (c) 2010-2018 Osman Shoukry
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.openpojo.reflection.java.bytecode.asm;

/**
 * Class loader that defines in memory the bytecode of the subclasses generated by ASM.
 *
 * @author oshoukry
 */
public class SimpleClassLoader extends ClassLoader {

	/**
	 * Defines a class in memory from its bytecode.
	 *
	 * @param classBytes
	 *     The bytecode of the class.
	 * @param className
	 *     The fully qualified name to give it.
	 * @return the newly defined class.
	 * @throws ClassNotFoundException
	 *     If the bytecode cannot be defined.
	 */
	public Class<?> loadThisClass(byte[] classBytes, String className) throws ClassNotFoundException {
		final Class<?> definedClass = defineClass(className, classBytes, 0, classBytes.length);
		resolveClass(definedClass);
		return loadClass(className);
	}

	/**
	 * Creates an instance ready to use.
	 */
	public SimpleClassLoader() {
	}
}
